### ISSUE TITLE
Arduino test suites not working on arduino-1.0-beta2 [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#621]
This is [Issue 621](http://code.google.com/p/arduino/issues/detail?id=621) moved from a Google Code project.
Added by 2011-09-02T22:15:19.000Z by [oldchurc...@gmail.com](http://code.google.com/u/105090555626527752475/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (Invalid).

Original labels: Type-Defect, Priority-Medium
### Original description

**What steps will reproduce the problem?**
1. Open ATS_Skeleton under Examples->ArduinoTestSuite
2. Click Verify

**What is the expected output? What do you see instead?**
# Expected

No errors
# Actual

In file included from C:\Program Files\arduino-0022\arduino-beta\arduino-1.0-beta2\libraries\ArduinoTestSuite/ArduinoTestSuite.h:11,
                 from ATS_Skeleton.cpp:11:
C:\Program Files\arduino-0022\arduino-beta\arduino-1.0-beta2\hardware\arduino\cores\arduino/Arduino.h:203:26: error: pins_arduino.h: No such file or directory

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

http://files.arduino.cc/downloads/arduino-1.0-beta2.zip

Win XP

Mega ADK
