### PR TITLE
Adding ARM builds

### PR DESCRIPTION
**Pull request by CRImier**
Hello!

Sorry for the delay. Here are the proposed changes to build.xml file for ARM architecture support, as discussed at https://github.com/arduino/Arduino/issues/3334. It works on Raspbian Wheezy&Jessie if compiled on Raspbian Wheezy, and on Jessie if compiled with Jessie. 
It all works, but there's a need either to natively compile on ARM or cross-compile. I could help with both. Same goes about libastyle and toolchain-avr - they either need to be cross-compiled or compiled on an ARM machine. I did all the compiling on ARM machine, and it worked great.

### CODE REVIEW

**Comment by ffissore** [comment]
Thank you @CRImier 
I think you should first provide proper instructions for packing an ARM version of the toolchain by submitting a PR to https://github.com/arduino/toolchain-avr
I'm reviewing https://github.com/arduino/astyle/pull/3 right now
Only AFTER we start building the ARM version on our own and publish the result on our server, we can merge this PR

**Comment by ffissore** [comment]
Argh, no, I'll review https://github.com/arduino/astyle/pull/3 on September

**Comment by NicoHood** [comment]
Raspberry now has a jessie build with 4.1 kernel and arm6/7
https://www.raspberrypi.org/blog/raspbian-jessie-is-here/

**Comment by ffissore** [comment]
I'm sorry but everything that has do with supporting another operating system is going down in my priority list. I don't expect to work on this for the coming months.

**Comment by NicoHood** [comment]
@CRImier could you please update the PR? Debian Jessie is out now (for the raspi) and I think wheezy support can be dropped if it adds more complexibility?

@ffissore As far as I understood https://github.com/arduino/astyle/pull/3 is required to build this. Why dont you just add it? If it doesnt work, then it wont hurt anyways since arm is just an optional community addition. But since the build system relies on hardcoded download links (as far as I understood) this makes it complicated to patch this?

**Comment by NicoHood** [comment]
I resolved the merging conflicts:
https://github.com/CRImier/Arduino/commit/faaa39d814ffbf3dad9a83cbcf0be3df8584cdf2

However I need an arm version of libastyle. I am currently not able to recompile it on my linux x64 nor arm machine.
pi@raspberrypi ~/Documents/Arduino/astyle $ ./arm.bash 
rm -f obj/*.o bin/*astyle*
g++ -DASTYLE_JNI -fPIC -fvisibility=hidden -DNDEBUG -W -Wall -fno-rtti -fno-exceptions -Os -I/usr/lib/jvm/default-java/include -I/usr/lib/jvm/default-java/include/linux -c -o obj/astyle_main_sj.o ../../src/astyle_main.cpp
In file included from ../../src/astyle_main.cpp:51:0:
../../src/astyle_main.h:55:18: fatal error: jni.h: No such file or directory
  #include <jni.h>
                  ^
compilation terminated.
Makefile:111: recipe for target 'obj/astyle_main_sj.o' failed
make: *** [obj/astyle_main_sj.o] Error 1
```

Any ideas?

If I have compiled libastyle, where should I place it, since its not downloaded within the .zip file automatically?
```

**Comment by NicoHood** [comment]
Now the question is where to get the avr-gcc from. I tried with my raspi:
```bash
sudo apt-get install gcc-avr
tar -jcvf avr-gcc-4.8.1-arduino5-armhf-pc-linux-gnu.tar.bz2 /usr/bin/avr-gcc-4.8.1 
md5sum avr-gcc-4.8.1-arduino5-armhf-pc-linux-gnu.tar.bz2 
sha1sum avr-gcc-4.8.1-arduino5-armhf-pc-linux-gnu.tar.bz2 
shasum avr-gcc-4.8.1-arduino5-armhf-pc-linux-gnu.tar.bz2 
sha256sum avr-gcc-4.8.1-arduino5-armhf-pc-linux-gnu.tar.bz2 
```

The checksum seems to be different, so I guess its the wrong file. where to get it from? Same question for avrdude-6.0.1-arduino5-armhf-pc-linux-gnu.tar.bz2

**Comment by NicoHood** [comment]
I changed the checksums (might differ due to newer compiler) and the build tool asked me the version number and name. It gave me a successful build.

However the IDE starts under raspbian wheezy armhf7 but then crashes with a java error
`java.lang.UnsupportedClassVersionError: processing/app/Base : Unsupported major.minor version 52.0`

Any ideas?

**Comment by lmihalkovic** [comment]
[NTS]

**Comment by NicoHood** [comment]
what?

**Comment by NicoHood** [comment]
Okay I solved some more errors, edited instructions above.

Problem now is a missing platform.keys.rewrite.txt file.

I tried as suggested:
```bash
cd ./linux/work/hardware/tools/avr/bin/
for i in *; do echo $i; rm $i; ln -s /usr/bin/$i $i; done
cd ../../../../../../
```

**Comment by NicoHood** [comment]
[exec] Picked up JAVA_TOOL_OPTIONS: 
     [exec] WARNING: Error loading hardware folder /home/pi/Documents/Arduino/Arduino/build/linux/work/hardware/arduino
     [exec]   No valid hardware definitions found in folder arduino.
     [exec] java.io.FileNotFoundException: /home/pi/Documents/Arduino/Arduino/build/linux/work/hardware/platform.keys.rewrite.txt (No such file or directory)
     [exec] java.io.FileNotFoundException: /home/pi/Documents/Arduino/Arduino/build/linux/work/hardware/platform.keys.rewrite.txt (No such file or directory)
     [exec] java.lang.IllegalStateException: Menu has no enabled items
     [exec] 	at processing.app.Base.selectFirstEnabledMenuItem(Base.java:1572)
     [exec] 	at processing.app.Base.rebuildBoardsMenu(Base.java:1422)
     [exec] 	at processing.app.Base.<init>(Base.java:297)
     [exec] 	at processing.app.Base.guardedMain(Base.java:222)
     [exec] 	at processing.app.Base.main(Base.java:136)

**Comment by NicoHood** [comment]
Okay I got it running fully. Full instructions above.

It might look a lot more complicated than it is. Basically you just need to compile and organize 5 binaries first (avrdude, avr-gcc, arduino-builder, ctags, astyle). Then you just hit ant build as usual.

If Arduino.cc could provide those arm binaries it would make the build process as easy as for x64 and others. No special changes, except the commits (for build.xml) I mentioned above are required.

Any chance to get arm support?

**Comment by TXCodeDancer** [comment]
@NicoHood I thought you'd be interested to know that I was able to follow your detailed instruction and build/install Arduino 1.6.7 on my Raspberry Pi running Ubuntu MATE 15.10. Thank you so much for documenting and sharing your efforts. Now my RPi will actually be useful as a development platform.

**Comment by facchinm** [comment]
Hi @NicoHood  and @TXCodeDancer ,
we decided not to provide an ARM build directly but if you could package up a fully self contained IDE (with Java, tools and all relative paths) we'll be glad to host it on the website (under a new Contributed section).
Nico, I'm sorry for the delay but I completely missed your post, great work by the way! Thank you very much! I'm setting up the Jenkins job for `arduino-builder` so it will always be in sync with the latest master

**Comment by NicoHood** [comment]
@facchinm Thanks, that'd be great. Could you please also add the same name schema as for the other platforms? Could you also host libastyle and the avr toolchain like this? This would make things a lot of faster since cross compiling for those tools did not work for me yet. Then it would be easier for other people to follow this instructions. Is it also possible to compile arm builds yourself? I dont know how the Arduino-Builder Builds are generated, but if we can do that with the other libs (asystle etc) too (officially) that'd be great.

@TXCodeDancer Do you also have this ctags bug? I opened a bug on arduino builder, that this get fixed first. I guess @ffissore has to fix it first so we can pack up a useful IDE.

So we have raspbian and ubuntu mate tested. Great!

**Comment by ffissore** [comment]
@NicoHood please see this https://groups.google.com/a/arduino.cc/forum/#!topic/developers/YJLX6AZHem4

**Comment by NicoHood** [comment]
@ffissore thanks for this note, I would have missed it. That is really sad, who else could do such a great job now, if not you?

**Comment by TXCodeDancer** [comment]
@NicoHood No, I didn't notice any Ctag issues. However, if they didn't stop me in my tracks I may have overlooked them.

@facchinm I'd love to contribute the Ubuntu MATE build, but I'm having problem with the Library Manager. The only way I've been able to add a library is with a ZIP file and I'm unable to update any libraries. If/when I figure out a fix or workaround I'll get back with you about how to share the build.

**Comment by ShorTie8** [comment]
I'm not really opposed to compiling things.
Actually, coming from Gentoo land, compiling is half the fun.
So, So, Sorry, I guess I never really comprehended all the little patching you did.
So I can see why you want to furnish everything, and hacking "may" not work right.

So what I've been playing with is expanding toolchain-avr so it will compile all files needed.
This could easily be setup as a support repo, instead of a add on.
https://github.com/ShorTie8/toolchain-avr/tree/arm
As is, it takes about 4-5 hours on my rpi2 to run, with most of it being the gcc compile time.
You end up with a files directory with everything in it.
avr-gcc, avrdude, bossac, ctags, coan, OpenOCD and libastylej so far.

./arch.arm.build.files.bash

It really does take a lot of digging to come up with all the stuff needed, so 1 central build script would be nice, or so I was thinking.
From there I was going to try to work the files directory into the building of the IDE&builder somehow.

In a way this might solve some problems.
In the land of Gentoo, when you upgrade a compiler it really is a long process.
1. you compile the new compiler
2. then you switch to the new compiler
3. re-compile the compiler
4. re-compile "everything" else (Yes, your whole system)

So once we got "our" gcc compiled.
Then we set it up to use the avr directory to compile everything else we need.
The re-compiling of the compiler might be a bit to far, But since our system is really like just 
autoconf, automake and binutils, that would not take to long.
That way we would know everything is at least compiled with the same compiler. If it matters.

Actually, I was also wondering if libtool should not be added ??
But I'm not sure how to bootstrap it .. :/~

Definitely a work in progress, But just wanted to through it out there as an idea.
Still would like to put all the downloads in a directory to keep the main directory cleaner,
And make verbose optional, no verbose does make it easier to follow, imho.

Have A Great Day
ShorTie

**Comment by NicoHood** [comment]
Hey Short, cool that you show up here! I wanted to ask a few questions, please dont blame me if they sound super stupid but I am a bit confused now...

How can we recompile the compiler if the compiler only compiles avr code and the compiler itself is arm/x64 architecture. So we cant do this for avr anyways.

But whats about the scripts you added to the toolchain? I can compile the toolchain in my rpi2 without any patches, so whats really different? I see you added libastyle and some other tools.

So thats how I understood your idea:
* use your fork to compile **all** required binaries
* git clone the Arduino IDE and apply the build patches
* merge the tools and compile the IDE

So the scripts just automate the steps ive listed above?

But for what do we need bossa etc if its not in the toolchain by default? It might be SAM related, I never used that.

**Comment by ShorTie8** [comment]
Just going with

locate g++
/usr/bin/arm-linux-gnueabihf-g++
/usr/bin/arm-linux-gnueabihf-g++-4.9
/usr/bin/g++
/usr/bin/g++-4.9
/usr/local/src/toolchain-avr/avr/avr/bin/g++
/usr/local/src/toolchain-avr/avr/bin/avr-g++


i see ... /avr/avr/bin/g++
so i was guessing that is the rest of the compiler we just compiled and twas usable .. :/~

The man thing is it's just 1 script that makes all the needed files for you into 1 place, thus making it easier, like so

    267195 Dec 16 17:52 avrdude-6.0.1-arduino5-armhf-pc-linux-gnu.tar.bz2
            65 Dec 16 17:52 avrdude-6.0.1-arduino5-armhf-pc-linux-gnu.tar.bz2.sha
24494315 Dec 16 17:52 avr-gcc-4.8.1-arduino5-armhf-pc-linux-gnu.tar.bz2
            65 Dec 16 17:52 avr-gcc-4.8.1-arduino5-armhf-pc-linux-gnu.tar.bz2.sha
      27659 Dec 16 17:53 bossac-1.6.1-arduino-arm-linux-gnueabihf.tar.gz
            65 Dec 16 17:53 bossac-1.6.1-arduino-arm-linux-gnueabihf.tar.gz.sha
  2341554 Dec 16 17:59 coan-5.2-armhf-pc-linux-gnu.tar.bz2
            65 Dec 16 17:59 coan-5.2-armhf-pc-linux-gnu.tar.bz2.sha
    336277 Dec 16 18:01 ctags-5.8-armhf-pc-linux-gnu.tar.bz2
            65 Dec 16 18:01 ctags-5.8-armhf-pc-linux-gnu.tar.bz2.sha
      80965 Dec 16 17:53 libastylej-armhf-linux-gnu.tar.bz2
            65 Dec 16 17:53 libastylej-armhf-linux-gnu.tar.bz2.sha
  1366515 Dec 16 18:13 OpenOCD-0.9.0-dev-arduino-arm-linux-gnueabihf.tar.bz2
            65 Dec 16 18:13 OpenOCD-0.9.0-dev-arduino-arm-linux-gnueabihf.tar.bz2.sha

**Comment by ShorTie8** [comment]
"But for what do we need bossa etc if its not in the toolchain by default? It might be SAM related, I never used that."

it's small and takes no time, so everyone has the same one
And I need/want it!, lol.

Merry Christmas to all
ShorTie

**Comment by NicoHood** [comment]
Okay now it makes sense. If the official Arduino Website could provide those binaries we could integrate them easier. However the ctag bug still needs to be fixed within arduino builder. I am still wondering why it doesnt show up in ubuntu mate, i should check this myself probably.

So @facchinm how do we do this now?

**Comment by ShorTie8** [comment]
Speaking of arduino builder, what is it's purpose other then making hacking harder ??
Actually everything from the platform key re-write on I really don't see much use for other then making it harder to hack the IDE, but I'm a chicken farmer not a programmer, lol.

Like as I propose above, If there was 1 easy to run script, to give all the stuff needed, instead of hours of searching for this, that or the other to compile this, that and the other, I feel, like me, peeps would be more prone to use the official stuff.

Make it easier not harder for peeps.

Why else do you think repo's are stuck back at like 1.0.5 ??

Official stuff does not have to come from just the Arduino Website does it??
If it is the Arduino version of the code compiled, does that not make it a official version ??

/rant off
comments welcomed

Have A Great Day
ShorTie

**Comment by ShorTie8** [comment]
and as a follow up to above

pi toolchain-avr # g++ --version
g++ (Raspbian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

pi toolchain-avr # /usr/local/src/toolchain-avr.mine/avr/avr/bin/./g++ --version
g++ (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


The system is using 4.9.2 and avr is at 4.8.1, big difference imho.
that is way I'm thinking it might be best to compile everything with the same version.
Then you have the Raspbian effect, got me on what all they have changed.

the above as a script, gcc.sh in toolchain-avr

#!/bin/bash
echo $PATH
g++ --version
TOOLS_BIN_PATH=`pwd`/avr/avr/bin
export PATH="$TOOLS_BIN_PATH:$PATH"
echo $PATH
g++ --version

**Comment by TXCodeDancer** [comment]
@NicoHood, I'm sorry but I'm afraid I spoke too soon and misled you. I thought the ctag error occurred when compiling the Arduino IDE, but I get the ctag error when trying to compile the Blink example.

Arduino: 1.6.7 (Linux), Board: "Arduino/Genuino Uno"
fork/exec {runtime.tools.ctags.path}/ctags: no such file or directory
Error compiling.

I was so fixated on the library installation issue that I never tried this basic test. I apologize for the confusion. I'll reread your ctag post and see if I can get past this issue.

**Comment by NicoHood** [comment]
Exactly. Its this bug:
https://github.com/arduino/arduino-builder/issues/79

Your comment about the libraries I do not really understand. This is the expected behavior? This is how I normally do it, when no lib manager package is available.

**Comment by TXCodeDancer** [comment]
Did I mention that I'm new here? :)

Re: Ctag error:
Yes, you documented the bug very well. I just didn't understand the context at first.

Re: Library Manager:
The thing is that the lib manager package seems to be available. For example OneWire is in the list of available packages, but when I click on it I never see an "Install" or "Update" button. 

This works smoothly with my windows installation (Arduino 1.6.6). Now I understand how to get the latest library package from my windows version and transfer it to my RPi.

Sorry about the extra noise.

**Comment by NicoHood** [comment]
It might be broken in the pi build. That might be another bug. But i do not have the time and hardware to check that again.

**Comment by NicoHood** [comment]
I just tested Ubuntu Mate as @TXCodeDancer did. I did not start the Arduino build, just tested the distro itself. And I must say it works extremely smooth. Even webbrowsing is possible, even youtube with just a bit of lag. Saying one **can** use this as "normal" PC. At least as simple edition.

So to conclude it really **would make sense** to provide arm builds. Not even for raspberry pi, also other systems could profit on that. However https://github.com/arduino/arduino-builder/issues/79 is still in the way, that I could provide any precompiled .zip file as (un)offical download. Any chance to have someone look into this? Its just a name resolving problem, it might be fixed easily.

**Comment by cmaglie** [comment]
@NicoHood 
I'll check the builder problem in the next days.

> So to conclude it really would make sense to provide arm builds

Once the various tools are build I guess that at some point they should be made available through package_index.json too, at least theoretically (until we get a sufficiently stable build job), so we should add a new "host" section for ARM in tools:

```json
        {
          "name": "avr-gcc",
          "version": "4.8.1-arduino2",
          "systems": [
            {
              "size": "24443285",
              "checksum": "SHA-256:c19a7526235c364d7f62ec1a993d9b495973ba1813869ccf0241c65905896852",
              "host": "i386-apple-darwin11",
              "archiveFileName": "avr-gcc-4.8.1-arduino2-i386-apple-darwin11.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/avr-gcc-4.8.1-arduino2-i386-apple-darwin11.tar.bz2"
            },
            {
              "size": "27152002",
              "checksum": "SHA-256:24a931877bee5f36dc00a88877219a6d2f6a1fb7abb989fd04556b8432d2e14e",
              "host": "x86_64-linux-gnu",
              "archiveFileName": "avr-gcc-4.8.1-arduino2-x86_64-pc-linux-gnu.tar.bz2",
              "url": "http://downloads.arduino.cc/tools/avr-gcc-4.8.1-arduino2-x86_64-pc-linux-gnu.tar.bz2"
            },
```

Even if it's not used better to have that in place already.
For that I need to know what the JVM return from these calls:

```java
System.getProperty("os.name");
System.getProperty("os.arch");
```

**Comment by NicoHood** [comment]
```java
class HelloWorld
{ 
        public static void main(String args[])
        {
           System.out.println("Hello World!");
           System.out.println(System.getProperty("os.name"));
           System.out.println(System.getProperty("os.arch"));
        }
}
```

```bash
Hello World!
Linux
arm
```

**Comment by cmaglie** [comment]
> Is there anything else I could/should do?

I forget the gcc target, please run a `gcc -v 2>&1 | grep Target` on my system is:

```
$ gcc -v 2>&1 | grep Target
Target: x86_64-linux-gnu
```

With those info I'm going to update this file:

https://github.com/arduino/Arduino/blob/master/arduino-core/src/cc/arduino/contributions/packages/HostDependentDownloadableContribution.java

This should be enough to provide downloads for arm when available.

**Comment by ShorTie8** [comment]
Been working on a script that lives in the Arduino world to build the IDE.
When done, it should work on any system not just ARM.
After the 1st run, if nothing has changed you should just get a bunch of
    "Your branch is up-to-date with 'origin/master'"
https://www.dropbox.com/s/eu69r7xcxlnjus3/Arduino_IDE_builder.bash?dl=0

and yes @NicoHood I made some stuff optional for you
It's almost done, but between the Chickens and Taxes, it may not get done till the weekend.

@CRImier  "gcc -v 2>&1 | grep Target" on my pi gives "arm-linux-gnueabihf"

The main question I have is the modified build.xml still build the other versions of the IDE ??
Or is it just for ARM's ??

@CRImier @facchinm Don't know if it would work or have any ill affects, but have you ever thought of file branding when configuring with  --with-pkgversion='Arduino $PKGVERSION' ??
Then you could add the logging of PKGVERSION in error reports so you know if it is a Arduino package/build ??

Have A Great Day

**Comment by ShorTie8** [comment]
can't do it in CONFARGS, but on the config, like ../gcc-4.8.1/configure --with-pkgversion="Arduino" $CONFARGS

to give

./avr-c++ --version
avr-c++ (Arduino ) 4.8.1
./g++ --version
g++ (Arduino ) 4.8.1

**Comment by NicoHood** [comment]
arch linux (pi2) gives:
```
Target: armv7l-unknown-linux-gnueabihf
```

I will check raspbian later and edit here. I think we should focus on raspbian and ubuntu mate, wanted to add arch anyways.

**Comment by Testato** [comment]
I'm on a BBB (BeagleBone), is it useful for testing ?

**Comment by TXCodeDancer** [comment]
@cmaglie Thanks for taking on  this effort!

Here are my results with Ubuntu MATE on a pi2:
$ java HelloWorld 
Hello World!
Linux
arm

$ gcc -v 2>&1 | grep Target
Target: arm-linux-gnueabihf

$ uname -a
Linux xxxx-RPi-00 4.1.15-v7+ #830 SMP Tue Dec 15 17:02:45 GMT 2015 armv7l armv7l armv7l GNU/Linux

Please let me know if I can provide any more useful information.

**Comment by NicoHood** [comment]
@Testato, please. If its the same name, we can use the build on BBB too (and you can test it if you like to).

Looking forward to see arm builds finally =)

**Comment by Testato** [comment]
Board: BBB (BeagleBoneBlack) on 
OS: Debian GNU/Linux 7.9 (wheezy)

~ # uname -a                                      
Linux beaglebone 3.8.13-bone70 #1 SMP Fri Jan 23 02:15:42 UTC 2015 armv7l GNU/Linux

~ # java HelloWorld                                                        
Hello World!
Linux
arm

~ # gcc -v 2>&1 | grep Target                        
Target: arm-linux-gnueabihf

**Comment by NicoHood** [comment]
Raspbian on a Pi Zero (the old one on arm6) gives the same results. So except arch-linux we could really build an arm build that works on all OS. I mean the current one from me should still work, with this workaround. But the builder should be patched and the binaries should be uploaded.

**Comment by ShorTie8** [comment]
@NicoHood on the ctags path issue, maybe try putting it in
Arduino/build/linux/work/tools-builder/ctags/5.8-arduino5
Also, and see if that fixes the path issue
it may not really need to be in 
arduino-builder-arm/tools/5.8-arduino5/
it maybe only be needed there if your gonna test run arduino-builder on cmd line

**Comment by NicoHood** [comment]
I just looked into my files and it is already there: `RaspiIDE/Arduino/build/linux/work/tools-builder/ctags/5.8-arduino5/`

**Comment by ShorTie8** [comment]
Got me, your just not putting it into the right place I do believe
Here is my script
wget https://raw.githubusercontent.com/ShorTie8/Arduino_IDE/master/Arduino_IDE_builder.bash

It seems to work fine on Raspberry and Odroid, other Linux's should work too...
It brand the files so you know there mine, lol.
Or Our's I guess .. :/~

Have Fun

**Comment by NicoHood** [comment]
I still do not understand what is wrong then. I will run your script and try out then.

I already added some comments to you commit:
https://github.com/ShorTie8/Arduino_IDE/commit/d181b654114b313b11f5fc0d23aa877370cf657a

**Comment by NicoHood** [comment]
For some reason your script exists after building go.
The last print on the bash is:
```
? unsafe [no test files]
```

Not sure why this happens. I used `sudo su` first and then run the script.

**Comment by ShorTie8** [comment]
I run it as root.
Tried to warn that is the only way it seemed to work for me .. :/~

**Comment by ShorTie8** [comment]
Here is a better write-up of the script maybe,  http://forum.arduino.cc/index.php?topic=372830.0

**Comment by NicoHood** [comment]
The toolchain script fails to download this file:
http://www.multiprecision.org/mpc/download/mpc-0.9.tar.gz

**Comment by NicoHood** [comment]
I works! I will search for the error I made. Now it should be easier to provide official arduino arm builds.

I will update this post after i find out new things. I guess it was an old go version that causes the builder to compile wrong.

**Comment by ShorTie8** [comment]
Added listSerialPortsC and fixed up some stuff
Think i got the naming and stuff right

**Comment by NicoHood** [comment]
You also noticed that I updated my ARM branch to the latest arduino? Do you also get this error when you try to start the IDE?

**Comment by ShorTie8** [comment]
no I haven't noticed it, but maybe may update github thing is not working right.
Are you pushing that a head of the current release ??
your gonna mess peeps up, as I did post that script around so others could use it.
I'm still around on irc

**Comment by facchinm** [comment]
Closing this one because all the discussion moved to https://github.com/arduino/Arduino/pull/4457
