### ISSUE TITLE
SdFat library [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#885]
This is [Issue 885](http://code.google.com/p/arduino/issues/detail?id=885) moved from a Google Code project.
Added by 2012-04-13T15:30:18.000Z by [pskor...@gmail.com](http://code.google.com/u/104411453460623127705/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Arduino sketches that depend on the sdfat library fail to compile on Arduino-1.0.1-rc2
2. I received the following error:
core.a(new.cpp.o): In function `__cxa_pure_virtual':
/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/new.cpp:17: multiple definition of `__cxa_pure_virtual'
SdFat/SdFat.cpp.o:/Users/usename/Documents/Arduino/libraries/SdFat/SdFat.cpp:62: first defined here
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/../../../../avr/bin/ld: Disabling relaxation: it will not work with multiple definitions

What version of the product are you using?
sdfatlib20111205 and SdFatBeta20120327

On what operating system?
Mac OS X

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/SD#16
