### ISSUE TITLE
Firmata broken in new-extension branch [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#519]
This is [Issue 519](http://code.google.com/p/arduino/issues/detail?id=519) moved from a Google Code project.
Added by 2011-04-04T23:35:39.000Z by [tom.i...@gmail.com](http://code.google.com/u/102867599453860860098/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (Duplicate).

Original labels: Type-Defect, Priority-Medium, Milestone-1.0
### Original description

Running the new-extension build on OSX 10.6, the following code:
```arduino
# include <Firmata.h>                

void setup() {
}

void loop() {
}
```
---

Generates the following errors:

There's also an issue with Firmata under new-extension:
```
/Users/tigoe/Documents/arduino development stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/libraries/Firmata/Firmata.cpp: In function 'void sendValueAsTwo7bitBytes(int)':
/Users/tigoe/Documents/arduino development stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/libraries/Firmata/Firmata.cpp:32: error: 'BYTE' was not declared in this scope
```
And several identical errors....
