### ISSUE TITLE
Arduino 1.0.5 doesn't open on OSX 10.5.8

### ISSUE THREAD

**Issue by greg-kennedy** [arduino/Arduino#1496]
Arduino 1.0.4 opens and works fine on OSX 10.5.8 Leopard.
The new version 1.0.5 fails to open.

```
macmini:Downloads grkenn$ open Arduino.app/
LSOpenFromURLSpec() failed with error -10810 for the file /Users/grkenn/Downloads/Arduino.app.
```

Console.app contains these log messages.

```
7/5/13 2:15:55 PM [0x0-0x320320].cc.arduino.Arduino[18446] [JavaAppLauncher Error] CallStaticVoidMethod() threw an exception 
7/5/13 2:15:55 PM [0x0-0x320320].cc.arduino.Arduino[18446] Exception in thread "main"  
7/5/13 2:15:55 PM [0x0-0x320320].cc.arduino.Arduino[18446] java.lang.NoClassDefFoundError: javax/swing/filechooser/FileNameExtensionFilter 
7/5/13 2:15:55 PM [0x0-0x320320].cc.arduino.Arduino[18446]  at java.lang.Class.forName0(Native Method) 
7/5/13 2:15:55 PM [0x0-0x320320].cc.arduino.Arduino[18446]  at java.lang.Class.forName(Class.java:242) 
7/5/13 2:15:55 PM [0x0-0x320320].cc.arduino.Arduino[18446]  at apple.launcher.LaunchRunner.loadMainMethod(LaunchRunner.java:56) 
7/5/13 2:15:55 PM [0x0-0x320320].cc.arduino.Arduino[18446]  at apple.launcher.LaunchRunner.run(LaunchRunner.java:112) 
7/5/13 2:15:55 PM [0x0-0x320320].cc.arduino.Arduino[18446]  at apple.launcher.LaunchRunner.callMain(LaunchRunner.java:51) 
7/5/13 2:15:55 PM [0x0-0x320320].cc.arduino.Arduino[18446]  at apple.launcher.JavaApplicationLauncher.launch(JavaApplicationLauncher.java:52) 
7/5/13 2:15:55 PM com.apple.launchd[71] ([0x0-0x320320].cc.arduino.Arduino[18446]) Exited with exit code: 1 
```

**Arduino 1.0.5 is using a class, javax/swing/filechooser/FileNameExtensionFilter, which is not present in JRE6 installed on OSX 10.5.8.**

Could the code referencing this class be reverted to 1.0.4 instead?
