### ISSUE TITLE
GSM library examples don't compile in Arduino 1.0.6.

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#2343]
I get this error when compiling, for example, GsmWebClient and ReceiveSMS.

Arduino: 1.0.6 (Mac OS X), Board: "DIY Cellphone (ATmega1284p, 8mhz)"
/Applications/Arduino.app/Contents/Resources/Java/libraries/GSM/GSM3ShieldV1ModemVerification.cpp: In member function 'String GSM3ShieldV1ModemVerification::getIMEI()':
/Applications/Arduino.app/Contents/Resources/Java/libraries/GSM/GSM3ShieldV1ModemVerification.cpp:72: error: conversion from 'int' to 'String' is ambiguous
/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WString.h:61: note: candidates are: String::String(const __FlashStringHelper_)
/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WString.h:59: note:                 String::String(const char_)
