### ISSUE TITLE
Arduino 1.8.7 Compile Failure (Works in 1.8.5)

### ISSUE THREAD

**Issue by SukkoPera** [arduino/Arduino#8014]
[This sketch](https://github.com/arduino/Arduino/files/2397217/ricette.txt) does not compile on Arduino 1.8.7, producing the following error:

    G:/Arduino/TAFFY/TAFFY_V1.3/TAFFY_V1.3.ino:65:19: error: 'ricetta' was not declared in this scope

This happens because the automatically generated function prototypes are inserted too early, before `struct ricetta` is defined, as shown in [the preprocessed sketch](https://github.com/arduino/Arduino/files/2397210/ricette.ino-187.txt).

This didn't happen in Arduino 1.8.5, which put the prototypes just before the setup() function. Preprocessor output is [here](https://github.com/arduino/Arduino/files/2397211/ricette.ino-185.txt).

This issue was raised by [user gianlucaf on the Arduino forums](http://forum.arduino.cc/index.php?topic=569238.0).

**Comment by facchinm** [comment]
Hi @SukkoPera ,
the issue has been already described by https://github.com/arduino/arduino-builder/issues/292 and fixed with https://github.com/arduino/arduino-builder/pull/294 .

I'd close this one to keep track of the issue in one place only; in the meantime, if you could test https://github.com/arduino/arduino-builder/pull/294#issuecomment-421968368 and report back it would be great :slightly_smiling_face:
