### ISSUE TITLE
Bug with the Due, the Arduino TFT and the TFT libary in 1.5.2

### ISSUE THREAD

**Issue by Alabamajack** [arduino/Arduino#1504]
In Arduino IDE 1.5.2 I've got these problem:
I want to use the Arduino TFT with my new Due. So copy the TFT libary from 1.0.5(like a supporter said) into the libraries folder. Then I want to compile a little programm for the TFT and then the compiler throw these exception:
"from sketch_jul11a.ino:1:
/home/myname/Arbeitsfläche/Software/arduino-1.5.2/libraries/TFT/utility/Adafruit_ST7735.h:28: fatal error: Adafruit_GFX.h: No such file or directory"
if I switch the Board into an Uno, its compile. So, I think, its any mistake of the ARM Linker or something like this!

**Comment by facchinm** [comment]
Fixed a long time ago (I believe). 
TFT library works perfectly with Due on 1.6 series
