### PR TITLE
Update bundled tools

### PR DESCRIPTION
**Pull request by facchinm**
Solves https://github.com/arduino/arduinoOTA/issues/2 and https://github.com/arduino/avrdude-build-script/issues/4
Should also solve https://github.com/arduino/Arduino/issues/5845, #5430  and https://github.com/arduino/Arduino/issues/2989 . A test appx for Windows10 will be generated after the build for extended testing

### CODE REVIEW

**Comment by b-rohit** [comment]
I got the following error>
Arduino: 1.8.2 (Windows 10), Board: "Arduino/Genuino Uno"

In file included from E:\Dw\arduino-mavlink-master\ArduinoMAVLink\ArduinoMAVLink.ino:2:0:

C:\Users\Rohit\Downloads\arduino-PR-5863-BUILD-637-windows\arduino-PR-5863-BUILD-637\libraries\FastSerial/FastSerial.h:47:3: error: #error Must include FastSerial.h before the Arduino serial driver is defined.

 # error Must include FastSerial.h before the Arduino serial driver is defined.
   ^
exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by facchinm** [comment]
@b-rohit , does it work in 1.8.1?

**Comment by matthijskooijman** [comment]
@b-rohit, unless I'm totally misunderstanding, it seems that's a new bug report, completely unrelated to this PR, so please post is as such. If you do, include more details, such as a (preferably as small as possible) sketch that reproduces the problem and why you think this is a bug in the Arduino IDE. If you're unsure, perhaps contact the library maintainer first to help resolve your problem.

**Comment by b-rohit** [comment]
no I got the same error in 1.8.1

**Comment by matthijskooijman** [comment]
Hmm, looking at the paths in your error output seems you are testing this PR, so I was mistaken. However, it doesn't look like a problem that is related to the changes in this PR, so indeed the question is whether it works in 1.8.1. And I just noticed your answer, so this is indeed a separate problem.

**Comment by per1234** [comment]
@b-rohit that issue is not related to any problem with the Arduino IDE and the sketch you're using has been [pretty much abandoned by the author](https://github.com/alaney/arduino-mavlink/commit/4d71dc5eecd4dda262237081a07c07963e8136ef#commitcomment-18880064). I believe I can help you but it's off topic here. Please post on the [Arduino Forum](http://forum.arduino.cc/index.php?board=4.0) and send me a PM with the link to the post at http://forum.arduino.cc/index.php?action=pm;sa=send;u=224903.

**Comment by jmandion** [comment]
For me, compilation is now sucessful! But I've got this error when uploading the code

Arduino:1.8.2 (Windows XP), Tarjeta:"Arduino/Genuino Uno"

```
___REMOVE___/bin/avrdude -C___REMOVE___/etc/avrdude.conf -v -patmega328p -carduino -PCOM4 -b115200 -D -Uflash:w:C:\TEMP/Blink.ino.hex:i 
java.io.IOException: Cannot run program "___REMOVE___/bin/avrdude": CreateProcess error=2, El sistema no puede hallar el archivo especificado
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:26)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:207)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
	at processing.app.SketchController.upload(SketchController.java:709)
	at processing.app.SketchController.exportApplet(SketchController.java:682)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2190)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede hallar el archivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more
```

I'm going to test the last nighty build.

**Comment by jmandion** [comment]
The last nightly build worked perfectly! Thank you!

**Comment by cmaglie** [comment]
@jmandion what do you mean with "nightly build"?

please note that this patch, **at this time** is still not merged so it's **not** available in the Hourly build, but only in the build posted above.

To be clear if you want to test it you must use the file named **arduino-PR-5863-BUILD-638**.

**Comment by jmandion** [comment]
@cmaglie Interesting... Please, excuse my brevity in my previous comments. This evening, I've been testing an Arduino Uno with a laptop running Windows XP SP3.

First, I downloaded Arduino IDE 1.8.1 and my arduino was successfully detected. I tried to run the Blink example, but I got issue #2989 
Next, I changed my build.path to C:\TEMP and moved my arduino installation to C:\Arduino to get paths without blank characters, but issue #2989 persisted.

Then, I reached this patch and downloaded arduino-PR-5863-BUILD-638. It solved issue #2989 and I could successfully link all the objects. However, when I tried to upload the executable to the arduino, I got the error I posted before: the "__REMOVE__" string in some paths. 

Finally, I downloaded the hourly build (whose filename is arduino-nightly-windows.zip, this is the reason of my bad understanding about the timing of the testing builds). I've successfully compiled and uploaded the Blink example to my arduino.

**Comment by facchinm** [comment]
The `avrdude` not found error (aka __REMOVE__) is "expected" since the avr core in this PR is not yet released and the tools definition gets overridden by the "official" json file. The important thing here is solving the compilation problem, however I'll add a temporary hack to make avrdude working again. 
The fact that nightly compiles the Blink sketch without any problem is quite puzzling... Could you paste here the verbose output of the three compilations (1.8.1, nightly and PR-5863) ? Thanks a lot

**Comment by jmandion** [comment]
Sorry for the delay. These are the outputs of the three compilations. Some messages are in Spanish, but I think they are understandable.

[Blink-Compilation-hourly.txt](https://github.com/arduino/Arduino/files/728002/Blink-Compilation-hourly.txt)
[Blink-Compilation-PR-5863-BUILD-638.txt](https://github.com/arduino/Arduino/files/728004/Blink-Compilation-PR-5863-BUILD-638.txt)
[Blink-Compilation-v1.8.1.txt](https://github.com/arduino/Arduino/files/728003/Blink-Compilation-v1.8.1.txt)

**Comment by bmd1103** [comment]
Build 645 worked for me so far.

**Comment by per1234** [comment]
Arduino forum user [stuart0 ](http://forum.arduino.cc/index.php?action=profile;u=568476)has been using test build 638 of this PR since 2017-01-18 on Windows XP without encountering https://github.com/arduino/Arduino/issues/2989 once. Prior to using the test build they did experience https://github.com/arduino/Arduino/issues/2989 multiple times. I will update if stuart0 reports any results to the contrary. I'm relaying the report because they don't have a GitHub account.

References:
original: https://forum.arduino.cc/index.php?topic=310950.msg3090378#msg3090378
latest update: http://forum.arduino.cc/index.php?topic=436394.msg3118041#msg3118041

**Comment by cmaglie** [comment]
Let's put the updated tools in the hourly, so a wider audience can test them.

**Comment by bmd1103** [comment]
Spoke too soon - I'm now getting
Linking everything together...
"C:\Program Files\Arduino_1.8\hardware\tools\avr/bin/avr-gcc"  -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections,--relax -mmcu=atmega2560  -o "C:\Temp1/Motors1.ino.elf" "C:\Temp1\sketch\Motor.cpp.o" "C:\Temp1\sketch\Motors1.ino.cpp.o" "C:\Temp1/core\core.a" "-LC:\Temp1" -lm
c:/program files/arduino_1.8/hardware/tools/avr/bin/../lib/gcc/avr/4.9.2/../../../../avr/bin/ld.exe: unrecognized option '-plugin'

c:/program files/arduino_1.8/hardware/tools/avr/bin/../lib/gcc/avr/4.9.2/../../../../avr/bin/ld.exe: use the --help option for usage information

collect2.exe: error: ld returned 1 exit status

So the collect2.exe error is coming up because of the unrecognised -plugin option.

**Comment by facchinm** [comment]
@bmd1103 are you testing the nightly or the PR build? Both should have no problem with linker plugins, so I bet there is something wrong going on here.
