### ISSUE TITLE
Arduino IDE 2.0 RC on Ubuntu is a total disaster!

### ISSUE THREAD

**Issue by maciejmiklas** [arduino/Arduino#11748]
I've installed latest RC on latest Ubuntu. I'm not getting any error on console, but the whole IDE is totaly unstable, so I'm not sure how this could be a release candidate?

1) I have small sketch, only few files, but for most of the time I can see in bottom corner Indexing .... and Building....  Manual build takes 2 seconds.
2) Formater stops working after a while, IDE has to be restarted in order to fix it
3) Menu displays key shortcuts but those are already used in Ubuntu, and instead other key shortcuts are working. Meaning: displayed shortcuts are incorrect. 
4) I have few cpp and h files, after few minutes IDE shows compilation errors but there are none. Restart helps here.
5) Jumping to declaration stops working after a few minutes as well.

Basically I have to restart IDE every few minutes, otherwise is shows non existing errors, formater is not working.  

I've been using Eclipse for development and I'm going back to Eclipse, because it's not possible to work with RC 2.0
