### ISSUE TITLE
Matrix library broken in new-extension branch [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#520]
This is [Issue 520](http://code.google.com/p/arduino/issues/detail?id=520) moved from a Google Code project.
Added by 2011-04-04T23:36:35.000Z by [tom.i...@gmail.com](http://code.google.com/u/102867599453860860098/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (Invalid).

Original labels: Type-Defect, Priority-Medium, Milestone-1.0
### Original description

Running the new-extension build on OSX 10.6, the following code:
```arduino
# include <Matrix.h>                // swap out whatever library is appropriate below

void setup() {
}

void loop() {
}
```
---

Generates the following errors:
```
/Users/tigoe/Documents/arduino development stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/libraries/Matrix/Matrix.cpp:41:20: error: Sprite.h: No such file or directory
/Users/tigoe/Documents/arduino development stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/libraries/Matrix/Matrix.cpp: In member function 'void Matrix::write(uint8_t, uint8_t, Sprite)':
```
