### ISSUE TITLE
IRremote.h error in 1.6.0 & 1.6.1

### ISSUE THREAD

**Issue by jmcos** [arduino/Arduino#2791]
I get the following compilation error when referencing IRremote.h:

Arduino: 1.6.1 (Windows 7), Board: "Arduino Uno"

C:\Program Files (x86)\Arduino\libraries\RobotIRremote\src\IRremoteTools.cpp:5:16: error: 'TKD2' was not declared in this scope

 int RECV_PIN = TKD2; // the pin the IR receiver is connected to

                ^
Error compiling.

**Comment by PaulStoffregen** [comment]
This was supposed to be fixed in 1.6.1.

Can you please post a copy of the sketch you're compiling?

Are you absolutely certain you installed the IRremote library in a location Arduino can access?

**Comment by jmcos** [comment]
int receiverpin = 11;#include <IRremote.h>
IRrecv irrecv(receiverpin);
decode_results results;void setup() {
Serial.begin(9600);
irrecv.enableIRIn();
}void loop() {
if (irrecv.decode(&results))
{
 Serial.print(results.value, HEX);
 Serial.print(" ");
 irrecv.resume();
}

---------- Original Message ----------

**Comment by ffissore** [comment]
It compiles fine with 1.6.1 and the latest IRRemote library from https://github.com/shirriff/Arduino-IRremote

**Comment by ffissore** [comment]
Actually, a final closing curly brace is missing, but, once added, it compiles fine

**Comment by jmcos** [comment]
Federico,   I downloaded the latest IRRemote library from the website, unzipped it and placed the header file in the correct directory.  The file is dated 3/10/2015 1:54 PM.  I recompiled and got the same error.  I opened IRremote.h and couldn't find TKD2. James

---------- Original Message ----------

**Comment by PaulStoffregen** [comment]
What *exactly* do you mean by "and placed the header file in the correct directory".

You're almost certainly installing IRremote incorrectly.  You're supposed to unzip the whole thing into Documents/Arduino/libraries.  In that folder is a small text file with instructions.

This isn't an issue with Arduino.  Version 1.6.0 had trouble.  1.6.1 is fixed.  This issue should be closed, and end-user tech support should be done via the forum.

**Comment by agdl** [comment]
Like @PaulStoffregen said should be closed and the issue should be discussed on the forum in case of necessity
