### ISSUE TITLE
Arduino Yun compiler version 1.5.7 cant compile

### ISSUE THREAD

**Issue by comp-hx** [arduino/Arduino#2265]
Hello,

I was using arduino version 1.0.5 on UBUNTU everything work fine.

Then I bought arduino YUN, upgraded to arduino 1.5.7.

Now my program that worked before with arduino 1.0.5 does not even compile with 1.5.7
At the top, my program include these:
# include < avr/interrupt.h >
# include < avr/io.h >
# include "Wire.h"

Now I get this error message:

Arduino: 1.5.7 (Linux), Board: "Arduino Yún"

Build options changed, rebuilding all
Using library Wire in folder: /home/user/arduino/arduino-1.5.7/hardware/arduino/avr/libraries/Wire (legacy)

/home/user/arduino/arduino-1.5.7/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -MMD -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=157 -DARDUINO_AVR_YUN -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8041 -DUSB_MANUFACTURER= -DUSB_PRODUCT="Arduino Yun" -I/home/user/arduino/arduino-1.5.7/hardware/arduino/avr/cores/arduino -I/home/user/arduino/arduino-1.5.7/hardware/arduino/avr/variants/yun -I/home/user/arduino/arduino-1.5.7/hardware/arduino/avr/libraries/Wire /tmp/build4257317746437848659.tmp/program.cpp -o /tmp/build4257317746437848659.tmp/program.cpp.o 
program.ino: In function 'void Timer2init()':
program.ino:260:3: error: 'TCCR2B' was not declared in this scope
program.ino:262:3: error: 'TCNT2' was not declared in this scope
program.ino:265:3: error: 'TCCR2A' was not declared in this scope
program.ino: In function 'void setup()':
program.ino:550:3: error: 'TCCR2B' was not declared in this scope

Anybody can help?

Thanks
