### ISSUE TITLE
SPI Library broken in new-extension branch [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#518]
This is [Issue 518](http://code.google.com/p/arduino/issues/detail?id=518) moved from a Google Code project.
Added by 2011-04-04T23:34:17.000Z by [tom.i...@gmail.com](http://code.google.com/u/102867599453860860098/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (Invalid).

Original labels: Type-Defect, Priority-Medium, Milestone-1.0
### Original description

Running the new-extension build on OSX 10.6, the following code:
```arduino
# include <SPI.h>                // swap out whatever library is appropriate below

void setup() {
}

void loop() {
}
```
Generates the following errors:
```
In file included from /Users/tigoe/Documents/arduino development stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/libraries/SPI/SPI.h:15,
                from /Users/tigoe/Documents/arduino development stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/libraries/SPI/SPI.cpp:12:
/Users/tigoe/Documents/arduino development stuff/gitRepo/Arduino/build/macosx/work/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/pins_arduino.h:66: error: previous declaration of 'const uint16_t port_to_mode_PGM []' with 'C++' linkage
```
And several other identical errors on other lines of pins_arduino.h
