### ISSUE TITLE
undefined reference to _gettimeofday

### ISSUE THREAD

**Issue by gdsports** [arduino/Arduino#9413]
OS: Ubuntu 18.04 64-bit

When building the same source code, 1.8.9 works fine. But 1.8.10 and hourly both fail at the link step with `gettimeofdayr.c:(.text._gettimeofday_r+0xe): undefined reference to '_gettimeofday'`.

Defining the function in the sketch keeps the linker happy.

```
extern "C" {
  // This must exist to keep the linker happy but is never called.
  int _gettimeofday( struct timeval *tv, void *tzvp )
  {
    Serial.println("_gettimeofday dummy");
    uint64_t t = 0;  // get uptime in nanoseconds
    tv->tv_sec = t / 1000000000;  // convert to seconds
    tv->tv_usec = ( t % 1000000000 ) / 1000;  // get remaining microseconds
    return 0;  // return non-zero for error
  } // end _gettimeofday()
}
```

Build log: https://gist.github.com/gdsports/d0046f9f91b2bed66f0a0a2608064485

**Comment by gdsports** [comment]
Sorry, the description is wrong. The code does NOT compile correctly with 1.8.9 so this appears to the an STM32duino problem.
